version: '3'
services:
  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - ./redis-data:/data
  bot:
    build:
      dockerfile: Dockerfile
      context: .
    command: pipenv run python3 ./lunch_bot.py
    volumes:
      - ./lunch_bot:/root/lunch_bot
    working_dir: /root/lunch_bot

volumes:
  redis-data:
