version: '3'
services:
  redis:
    image: redis:4.0.5-alpine
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - ./redis-data:/data
  bot:
    build:
      dockerfile: Dockerfile
      context: .
    command: pipenv run python3 /root/bot/redis_test.py
    volumes:
      - ./bot:/root/bot
    working_dir: /root

volumes:
  redis-data:
